# Generated by Django 5.1 on 2024-08-25 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashborad", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="profile",
        ),
        migrations.DeleteModel(
            name="FirstAid",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Diagnosis",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
