# Generated by Django 5.1 on 2024-08-25 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashborad", "0002_remove_diagnosis_doctor_remove_diagnosis_patient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Entrez la spécialité médicale du médecin, par exemple : Cardiologue, Dermatologue, etc.",
                        max_length=255,
                        verbose_name="Spécialité",
                    ),
                ),
                (
                    "hospital_affiliation",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'hôpital ou de la clinique où le médecin est affilié.",
                        max_length=255,
                        null=True,
                        verbose_name="Affiliation Hospitalière",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Entrez le numéro de licence professionnelle du médecin.",
                        max_length=255,
                        verbose_name="Numéro de Licence",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone ou de contact professionnel du médecin.",
                        max_length=15,
                        null=True,
                        verbose_name="Numéro de Contact",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Entrez la date de naissance du patient.",
                        verbose_name="Date de Naissance",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Entrez un résumé des antécédents médicaux du patient, y compris les maladies chroniques, les opérations, etc.",
                        null=True,
                        verbose_name="Historique Médical",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        help_text="Entrez le nom et le numéro de téléphone de la personne à contacter en cas d'urgence.",
                        max_length=255,
                        verbose_name="Contact d'Urgence",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.CharField(
                        blank=True,
                        help_text="Entrez les conditions médicales chroniques du patient, par exemple : Diabète, Hypertension, etc.",
                        max_length=255,
                        null=True,
                        verbose_name="Conditions Chroniques",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
