# Generated by Django 5.1 on 2024-08-25 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashborad", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="Medecin",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
