# Generated by Django 5.1 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashborad", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact",
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(
                default="Unknown",
                help_text="Entrez le nom de la personne à contacter en cas d'urgence.",
                max_length=255,
                verbose_name="Nom du Contact d'Urgence",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                default="Unknown",
                help_text="Entrez le numéro de téléphone de la personne à contacter en cas d'urgence.",
                max_length=20,
                verbose_name="Numéro du Contact d'Urgence",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medecin",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone ou de contact professionnel du médecin.",
                max_length=20,
                null=True,
                verbose_name="Numéro de Contact",
            ),
        ),
    ]
