# Generated by Django 5.1 on 2024-08-25 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashborad", "0006_remove_patient_emergency_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="Medecin",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
