# Generated by Django 5.1 on 2024-08-25 20:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashborad", "0009_alter_patient_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domicile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symptom",
                    models.CharField(
                        help_text="Symptôme observé qui nécessite une assistance à domicile.",
                        max_length=255,
                        verbose_name="Symptôme",
                    ),
                ),
                (
                    "explanation",
                    ckeditor.fields.RichTextField(
                        help_text="Explication du symptôme et des raisons possibles.",
                        verbose_name="Explication",
                    ),
                ),
                (
                    "assistance_method",
                    ckeditor.fields.RichTextField(
                        help_text="Méthode ou procédure pour assister la personne à domicile.",
                        verbose_name="Méthode d'assistance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titre de la route de premiers secours.",
                        max_length=255,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        help_text="Description détaillée de la route de premiers secours.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "steps",
                    ckeditor.fields.RichTextField(
                        help_text="Étapes à suivre pour fournir les premiers secours.",
                        verbose_name="Étapes",
                    ),
                ),
            ],
        ),
    ]
